"""Generate a report, record it, archive it. The one place that does all three.

Both entry points come through here - the dashboard button (`on_demand`) and
the daily course-end job (`course_end`) - so a report generated by a button and
one generated by the scheduler are byte-for-byte the same document with a
different `trigger`.

Nothing here talks to WhatsApp. The scheduler owns the decision to message
somebody; this module owns the PDF.
"""

from __future__ import annotations

import logging

from sqlmodel import col, select

from app.db import session_scope
from app.models import REPORT_KINDS, REPORT_TRIGGERS, Report, Schedule
from app.reports import caretaker_pdf, data, doctor_pdf, storage

log = logging.getLogger(__name__)


def render(kind: str, patient_id: str, medicine_id: str,
           lang: str = "en") -> bytes:
    """The PDF bytes for one report. No database writes."""
    if kind not in REPORT_KINDS:
        raise ValueError(f"kind must be one of {REPORT_KINDS}, not {kind!r}")
    if kind == "doctor":
        return doctor_pdf.build(patient_id, medicine_id)
    return caretaker_pdf.build(patient_id, medicine_id, lang=lang)


def generate(kind: str, patient_id: str, medicine_id: str, *,
             trigger: str = "on_demand", lang: str = "en",
             archive: bool = True) -> tuple[Report, bytes]:
    """Render one report, write its row, and archive the PDF.

    Returns the row and the bytes. The row is detached - the caller gets a
    plain object, not a live session.
    """
    if trigger not in REPORT_TRIGGERS:
        raise ValueError(f"trigger must be one of {REPORT_TRIGGERS}, not {trigger!r}")

    course = data.for_course(patient_id, medicine_id)
    blob = render(kind, patient_id, medicine_id, lang=lang)

    with session_scope() as session:
        row = Report(
            patient_id=patient_id,
            medicine_id=medicine_id,
            kind=kind,
            trigger=trigger,
            period_start=course.start_date,
            period_end=course.end_date,
            storage_key="",
        )
        # The key needs the row's id, which only exists once it has one.
        row.storage_key = storage.object_key(patient_id, row.id)
        session.add(row)
        session.commit()
        session.refresh(row)
        session.expunge(row)

    if archive:
        # A failed archive is logged, never raised: the caller already has the
        # bytes, and the endpoint can regenerate this row on demand forever.
        storage.try_upload(row.storage_key, blob)

    log.info("generated %s report %s for patient %s (%s)",
             kind, row.id, patient_id, trigger)
    return row, blob


def fetch(report_id: str) -> tuple[Report, bytes] | None:
    """An existing report by id, from the archive or regenerated.

    Regeneration is safe: every number in the document comes from the
    database, so a rebuilt PDF says exactly what the archived one said.
    """
    with session_scope() as session:
        row = session.get(Report, report_id)
        if row is None:
            return None
        session.expunge(row)

    blob = storage.download(row.storage_key) if row.storage_key else None
    if blob is not None:
        return row, blob

    if not row.medicine_id:
        log.error("report %s has no medicine and no archived copy", report_id)
        return None

    log.info("report %s not in the archive - regenerating", report_id)
    blob = render(row.kind, row.patient_id, row.medicine_id,
                  lang=_lang_for(row.patient_id))
    return row, blob


def _lang_for(patient_id: str) -> str:
    carers = data.caretakers_of(patient_id)
    return (carers[0].get("language") if carers else None) or "en"


def existing_kinds(patient_id: str, medicine_id: str,
                   trigger: str | None = None) -> set[str]:
    """Which report kinds already exist for this course.

    The course-end job uses this to stay idempotent - it runs daily and must
    not send the caretaker the same pair of reports every morning.
    """
    with session_scope() as session:
        query = (select(Report.kind)
                 .where(Report.patient_id == patient_id)
                 .where(Report.medicine_id == medicine_id))
        if trigger:
            query = query.where(Report.trigger == trigger)
        return set(session.exec(query).all())


def finished_courses() -> list[dict]:
    """Schedules whose last dose day has passed and that have no course-end
    reports yet.

    `end_date` is INCLUSIVE (see models.Schedule), so a course ending on the
    21st is finished from the 22nd onwards.
    """
    from app.scheduler.ticker import local_today

    today = local_today()
    with session_scope() as session:
        rows = session.exec(
            select(Schedule).where(col(Schedule.end_date) < today)
        ).all()
        courses = [{"schedule_id": s.id, "medicine_id": s.medicine_id,
                    "end_date": s.end_date} for s in rows]

    out: list[dict] = []
    for course in courses:
        with session_scope() as session:
            from app.models import Medicine
            medicine = session.get(Medicine, course["medicine_id"])
            if medicine is None:
                continue
            course["patient_id"] = medicine.patient_id

        done = existing_kinds(course["patient_id"], course["medicine_id"],
                              trigger="course_end")
        if not set(REPORT_KINDS) <= done:
            course["missing"] = sorted(set(REPORT_KINDS) - done)
            out.append(course)
    return out
